# Generated by Django 4.2.6 on 2023-10-15 02:08

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gerencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.CharField(max_length=255)),
                ('prazo', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today)])),
            ],
            options={
                'ordering': ['prazo'],
            },
        ),
        migrations.CreateModel(
            name='MetaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Concluído', 'Concluído')], max_length=50)),
                ('gerencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisitos.gerencial')),
            ],
        ),
        migrations.CreateModel(
            name='Organizacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=255)),
                ('estrategia', models.TextField()),
                ('meta_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizacionais', to='requisitos.metamodelo')),
            ],
        ),
        migrations.CreateModel(
            name='ModeloIntermediario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacao_comum', models.TextField()),
                ('meta_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_intermediarios', to='requisitos.metamodelo')),
            ],
        ),
        migrations.AddField(
            model_name='gerencial',
            name='meta_modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gerenciais', to='requisitos.metamodelo'),
        ),
        migrations.CreateModel(
            name='Desenvolvimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisito_funcional', models.TextField()),
                ('requisito_nao_funcional', models.TextField()),
                ('meta_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desenvolvimentos', to='requisitos.metamodelo')),
            ],
        ),
        migrations.CreateModel(
            name='Ambiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fator_externo', models.CharField(max_length=255)),
                ('impacto', models.TextField()),
                ('meta_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientais', to='requisitos.metamodelo')),
            ],
        ),
    ]
