# Generated by Django 4.2.6 on 2023-10-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelointermediario',
            name='meta_modelo',
        ),
        migrations.AddField(
            model_name='modelointermediario',
            name='meta_modelos',
            field=models.ManyToManyField(related_name='modelos_intermediarios', to='requisitos.metamodelo'),
        ),
    ]
