# Generated by Django 4.2.6 on 2023-11-07 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requisitos', '0002_remove_modelointermediario_meta_modelo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, choices=[('FUNC', 'Funcional'), ('NAOFUNC', 'Não Funcional')], max_length=8, null=True)),
                ('tipo', models.CharField(choices=[('NEG', 'Negócio'), ('CLI', 'Cliente'), ('SIS', 'Sistema'), ('USR', 'Usuário')], max_length=3)),
                ('prioridade', models.CharField(choices=[('ESS', 'Essencial'), ('IMP', 'Importante'), ('DES', 'Desejável')], max_length=3)),
                ('status', models.CharField(choices=[('PROP', 'Proposto'), ('APRO', 'Aprovado'), ('IMPL', 'Implementado'), ('TEST', 'Testado'), ('CONC', 'Concluído')], max_length=4)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='desenvolvimento',
            name='requisito_funcional',
        ),
        migrations.RemoveField(
            model_name='desenvolvimento',
            name='requisito_nao_funcional',
        ),
        migrations.AddField(
            model_name='metamodelo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='metamodelo',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='HistoricalRequisito',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, choices=[('FUNC', 'Funcional'), ('NAOFUNC', 'Não Funcional')], max_length=8, null=True)),
                ('tipo', models.CharField(choices=[('NEG', 'Negócio'), ('CLI', 'Cliente'), ('SIS', 'Sistema'), ('USR', 'Usuário')], max_length=3)),
                ('prioridade', models.CharField(choices=[('ESS', 'Essencial'), ('IMP', 'Importante'), ('DES', 'Desejável')], max_length=3)),
                ('status', models.CharField(choices=[('PROP', 'Proposto'), ('APRO', 'Aprovado'), ('IMPL', 'Implementado'), ('TEST', 'Testado'), ('CONC', 'Concluído')], max_length=4)),
                ('descricao', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical requisito',
                'verbose_name_plural': 'historical requisitos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMetaModelo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical meta modelo',
                'verbose_name_plural': 'historical meta modelos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoriaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('criterios_aceitacao', models.TextField()),
                ('estimativa', models.IntegerField(help_text='Estimativa de esforço ou tempo necessário')),
                ('prioridade', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em Progresso', 'Em Progresso'), ('Concluída', 'Concluída')], max_length=50)),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_usuario', to='requisitos.requisito')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='requisitos.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('descricao', models.CharField(max_length=255)),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='requisitos.requisito')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='requisitos.requisito')),
            ],
        ),
        migrations.CreateModel(
            name='CasoDeUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('ator_principal', models.CharField(max_length=100)),
                ('atores_secundarios', models.CharField(blank=True, max_length=100)),
                ('pre_condicoes', models.TextField(blank=True)),
                ('fluxo_principal', models.TextField()),
                ('fluxos_alternativos', models.TextField(blank=True)),
                ('pos_condicoes', models.TextField(blank=True)),
                ('prioridade', models.IntegerField(default=0)),
                ('requisitos', models.ManyToManyField(related_name='casos_de_uso', to='requisitos.requisito')),
            ],
        ),
        migrations.AddField(
            model_name='desenvolvimento',
            name='requisitos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'categoria__in': ['FUNC', 'NAOFUNC']}, related_name='desenvolvimentos', to='requisitos.requisito'),
        ),
        migrations.AddField(
            model_name='metamodelo',
            name='casos_de_uso',
            field=models.ManyToManyField(related_name='meta_modelos', to='requisitos.casodeuso'),
        ),
        migrations.AddField(
            model_name='metamodelo',
            name='historias_usuario',
            field=models.ManyToManyField(related_name='meta_modelos', to='requisitos.historiausuario'),
        ),
    ]
